### ISSUE TITLE
feat: tracking evmos token status in Osmosis with User Account Address

### ISSUE THREAD

**Issue by sigridjineth** [DAOForce/ParachuteDrop-LightClient#1]
## Implementation
* [x] with given address, get the balance of evmos (in osmosis) first https://github.com/DAOForce/ParachuteDrop-LightClient/commit/6f50a26883ee9a1c7f0a021b01392a1be2298fb0
* [x] get to know the message type of osmosis in locking token /unlocking token /joinpool/exitpool & how to communicate in grpc
 * all related modules in the [following link](https://docs.osmosis.zone/osmojs/)
 * Messages To Work with is the following
 A. DumpMsg: `beginUnlocking`, `beginUnlockingAll`, `lockTokens`, `superfluidUnbondLock`, `superfluidUndelegate`,
 B. HodlMsg: `JoinPool`, `LockTokens`, `lockAndSuperfluidDelegate`, `superfluidDelegate`
 C. Difference in context: `SwapExactAmountIn`, `SwapExactAmountOut`

* [x] utilize sonarpod api to query all account's transaction, then find messages only if the type on the above
 * when requesting with `/messages`, then it returns with the following response after filitering with (evmos) related msgs
 ```
 'TotalDumpMsgs': int,
 'TotalHodlMsgs': int,
 'Address': String,
 'TargetChain': string,
 'TokenDenom': string,
 'Msgs': {
    'DumpMsg': [
      {
        'MsgType': 'beginUnlocking',
        'TxHash': 'asbsd',
      },
    ],
    'HodlMsg': [
      {
        'MsgType': 'joinPool',
        'TxHash': 'asbsd',
      },
    ],
 }
 ```
 * call like this
 ```
 grpcurl -plaintext -d '{"hash": "F54E1C65DF27C20EE0D124DB897B59D4A70D2A93955303D5FA12642609258DE6"}' grpc.osmosis.zone:9090 cosmos.tx.v1beta1.Service/GetTx
 ```
 * osmosis only has `evmos` related pool in [#722](https://app.osmosis.zone/pool/722)
